### PR TITLE
migrates project to use gradle and android studio

### PR DESCRIPTION
**Pull request by Servus7**

### CODE REVIEW

**Comment by jcampbell05** [comment]
@Servus7  Thanks for this, I was wondering if we could update this project to remove any reference to NYXDigital. That was the old agency I worked for and this project is no longer sccociated with them.

I'm thinking the new bundle becomes:
`com.Nice.NiceSupportMapFragment`

What do you think ?

**Comment by Servus7** [comment]
@jcampbell05 The right naming would be `domain.company.application`. 

For example:

- `com.nice.nicesupportmapfragment`
- `com.nice.supportmapfragment`
- `com.jcampbell05.nicesupportmapfragment`
- `com.jcampbell05.supportmapfragment`
- `com.jcampbell.nicesupportmapfragment`
- `com.jcampbell.supportmapfragment`

**Comment by jcampbell05** [comment]
@Servus7  Cool which one do you think we should go with ?

**Comment by Servus7** [comment]
@jcampbell05 you are the repository owner and it's about the NiceSupportMapFragment: `com.jcampbell05.nicesupportmapfragment`

**Comment by jcampbell05** [comment]
@Servus7 Cool let's go with that :)

**Comment by jcampbell05** [comment]
Great Work! 🚀 🎸

**Pull request merged**
